//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenshotAnnotator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenshotAnnotator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Format(string key, params object[] args) {
            string format = ResourceManager.GetString(key, resourceCulture) ?? key;
            return string.Format(resourceCulture, format, args);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string _Technical_NsisLanguage {
            get {
                return ResourceManager.GetString("_Technical_NsisLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string _Technical_WingetLocale {
            get {
                return ResourceManager.GetString("_Technical_WingetLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Annotator.
        /// </summary>
        public static string App_DisplayName {
            get {
                return ResourceManager.GetString("App_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Accept.
        /// </summary>
        public static string Button_Accept {
            get {
                return ResourceManager.GetString("Button_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✕ Cancel.
        /// </summary>
        public static string Button_CancelX {
            get {
                return ResourceManager.GetString("Button_CancelX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ContextMenu_Open {
            get {
                return ResourceManager.GetString("ContextMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotator {0} : Copyright (c) 2025-{1} Siarhei Kuchuk.
        /// </summary>
        public static string Copyright_Text {
            get {
                return ResourceManager.GetString("Copyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Dialog_Export_Title {
            get {
                return ResourceManager.GetString("Dialog_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Project or Image.
        /// </summary>
        public static string Dialog_Import_Title {
            get {
                return ResourceManager.GetString("Dialog_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string FileType_AllFiles {
            get {
                return ResourceManager.GetString("FileType_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files.
        /// </summary>
        public static string FileType_AllSupported {
            get {
                return ResourceManager.GetString("FileType_AllSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotator Project.
        /// </summary>
        public static string FileType_AnnotatorProject {
            get {
                return ResourceManager.GetString("FileType_AnnotatorProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string FileType_Images {
            get {
                return ResourceManager.GetString("FileType_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Image.
        /// </summary>
        public static string FileType_JPEG {
            get {
                return ResourceManager.GetString("FileType_JPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Image.
        /// </summary>
        public static string FileType_PNG {
            get {
                return ResourceManager.GetString("FileType_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebP Image.
        /// </summary>
        public static string FileType_WebP {
            get {
                return ResourceManager.GetString("FileType_WebP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Screenshot Annotator - V{0} ].
        /// </summary>
        public static string Header_ScreenshotAnnotator {
            get {
                return ResourceManager.GetString("Header_ScreenshotAnnotator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        ///
        ///Please contact the developers with information saved on your desktop in
        ///&quot;{0}&quot;
        ///
        ///Application will now close..
        /// </summary>
        public static string ImproveIt_Message {
            get {
                return ResourceManager.GetString("ImproveIt_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges required to install for all users.
        ///Please run the installer as administrator or use /CURRENTUSER..
        /// </summary>
        public static string Installer_AdminRequired {
            get {
                return ResourceManager.GetString("Installer_AdminRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges are required to install for all users.
        ///
        ///Please either:
        ///- Choose &apos;Install for current user only&apos;, or
        ///- Run this installer as administrator.
        /// </summary>
        public static string Installer_AdminRequiredDetailed {
            get {
                return ResourceManager.GetString("Installer_AdminRequiredDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will be available for all users on this computer..
        /// </summary>
        public static string Installer_AllUsersDescription {
            get {
                return ResourceManager.GetString("Installer_AllUsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install for &amp;all users (requires administrator privileges).
        /// </summary>
        public static string Installer_AllUsersOption {
            get {
                return ResourceManager.GetString("Installer_AllUsersOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installer requires a x64 or arm64 version of Windows..
        /// </summary>
        public static string Installer_ArchRequired {
            get {
                return ResourceManager.GetString("Installer_ArchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended. The application will only be available for your user account..
        /// </summary>
        public static string Installer_CurrentUserDescription {
            get {
                return ResourceManager.GetString("Installer_CurrentUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install for &amp;current user only.
        /// </summary>
        public static string Installer_CurrentUserOption {
            get {
                return ResourceManager.GetString("Installer_CurrentUserOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing for:.
        /// </summary>
        public static string Installer_InstallingFor {
            get {
                return ResourceManager.GetString("Installer_InstallingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose whether you want to install Screenshot Annotator for yourself only or for all users of this computer..
        /// </summary>
        public static string Installer_InstallModeDescription {
            get {
                return ResourceManager.GetString("Installer_InstallModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select who can use this application.
        /// </summary>
        public static string Installer_InstallModeSubtitle {
            get {
                return ResourceManager.GetString("Installer_InstallModeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Installation Type.
        /// </summary>
        public static string Installer_InstallModeTitle {
            get {
                return ResourceManager.GetString("Installer_InstallModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch App.
        /// </summary>
        public static string Installer_LaunchApp {
            get {
                return ResourceManager.GetString("Installer_LaunchApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Print Screen hotkey.
        /// </summary>
        public static string Menu_EnablePrintScreenHotkey {
            get {
                return ResourceManager.GetString("Menu_EnablePrintScreenHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ File ].
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Menu_License {
            get {
                return ResourceManager.GetString("Menu_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Logs Folder.
        /// </summary>
        public static string Menu_OpenLogsFolder {
            get {
                return ResourceManager.GetString("Menu_OpenLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Projects _Folder.
        /// </summary>
        public static string Menu_OpenProjectsFolder {
            get {
                return ResourceManager.GetString("Menu_OpenProjectsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-Site.
        /// </summary>
        public static string Menu_WebSite {
            get {
                return ResourceManager.GetString("Menu_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Engine:.
        /// </summary>
        public static string Ocr_Engine {
            get {
                return ResourceManager.GetString("Ocr_Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text.
        /// </summary>
        public static string Ocr_ExtractButton {
            get {
                return ResourceManager.GetString("Ocr_ExtractButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages:.
        /// </summary>
        public static string Ocr_Languages {
            get {
                return ResourceManager.GetString("Ocr_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No OCR engines are available on this system..
        /// </summary>
        public static string Ocr_NoEngines {
            get {
                return ResourceManager.GetString("Ocr_NoEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable OCR, install Tesseract OCR and make sure it is in your system PATH.
        ///You can download it from the Tesseract GitHub page..
        /// </summary>
        public static string Ocr_NoEnginesHelp {
            get {
                return ResourceManager.GetString("Ocr_NoEnginesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing….
        /// </summary>
        public static string Ocr_Processing {
            get {
                return ResourceManager.GetString("Ocr_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Text:.
        /// </summary>
        public static string Ocr_Result {
            get {
                return ResourceManager.GetString("Ocr_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Additional language packs can be installed for Tesseract — check the Tesseract documentation..
        /// </summary>
        public static string Ocr_TesseractLangHint {
            get {
                return ResourceManager.GetString("Ocr_TesseractLangHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text.
        /// </summary>
        public static string Ocr_Title {
            get {
                return ResourceManager.GetString("Ocr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in Windows OCR can miss text. Screenshot Annotator also supports Tesseract OCR, which often extracts text better. Install Tesseract manually to use it here..
        /// </summary>
        public static string Ocr_WindowsTesseractHint {
            get {
                return ResourceManager.GetString("Ocr_WindowsTesseractHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Panel_Projects {
            get {
                return ResourceManager.GetString("Panel_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Panel_Properties {
            get {
                return ResourceManager.GetString("Panel_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Props_Bold {
            get {
                return ResourceManager.GetString("Props_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Props_Color {
            get {
                return ResourceManager.GetString("Props_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Props_Font {
            get {
                return ResourceManager.GetString("Props_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Props_Italic {
            get {
                return ResourceManager.GetString("Props_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Props_Size {
            get {
                return ResourceManager.GetString("Props_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and drag to select area, or adjust corner points. Use magnifier for precision. Press OK when ready..
        /// </summary>
        public static string Screenshot_Instructions {
            get {
                return ResourceManager.GetString("Screenshot_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Selection_Copy {
            get {
                return ResourceManager.GetString("Selection_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Selection_Delete {
            get {
                return ResourceManager.GetString("Selection_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text.
        /// </summary>
        public static string Selection_ExtractText {
            get {
                return ResourceManager.GetString("Selection_ExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        public static string Tool_Arrow {
            get {
                return ResourceManager.GetString("Tool_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur.
        /// </summary>
        public static string Tool_Blur {
            get {
                return ResourceManager.GetString("Tool_Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string Tool_Border {
            get {
                return ResourceManager.GetString("Tool_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callout.
        /// </summary>
        public static string Tool_Callout {
            get {
                return ResourceManager.GetString("Tool_Callout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Tool_Copy {
            get {
                return ResourceManager.GetString("Tool_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut -.
        /// </summary>
        public static string Tool_CutHorizontal {
            get {
                return ResourceManager.GetString("Tool_CutHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut |.
        /// </summary>
        public static string Tool_CutVertical {
            get {
                return ResourceManager.GetString("Tool_CutVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Tool_Export {
            get {
                return ResourceManager.GetString("Tool_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string Tool_Highlight {
            get {
                return ResourceManager.GetString("Tool_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Tool_Import {
            get {
                return ResourceManager.GetString("Tool_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Tool_New {
            get {
                return ResourceManager.GetString("Tool_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Tool_Note {
            get {
                return ResourceManager.GetString("Tool_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Tool_Paste {
            get {
                return ResourceManager.GetString("Tool_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string Tool_Screenshot {
            get {
                return ResourceManager.GetString("Tool_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Tool_Select {
            get {
                return ResourceManager.GetString("Tool_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw an arrow.
        /// </summary>
        public static string Tooltip_Arrow {
            get {
                return ResourceManager.GetString("Tooltip_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur an area.
        /// </summary>
        public static string Tooltip_Blur {
            get {
                return ResourceManager.GetString("Tooltip_Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a border/rectangle.
        /// </summary>
        public static string Tooltip_Border {
            get {
                return ResourceManager.GetString("Tooltip_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a callout.
        /// </summary>
        public static string Tooltip_Callout {
            get {
                return ResourceManager.GetString("Tooltip_Callout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse/Expand Projects Panel.
        /// </summary>
        public static string Tooltip_CollapseExpandPanel {
            get {
                return ResourceManager.GetString("Tooltip_CollapseExpandPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string Tooltip_Copy {
            get {
                return ResourceManager.GetString("Tooltip_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut image horizontally.
        /// </summary>
        public static string Tooltip_CutHorizontal {
            get {
                return ResourceManager.GetString("Tooltip_CutHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut image vertically.
        /// </summary>
        public static string Tooltip_CutVertical {
            get {
                return ResourceManager.GetString("Tooltip_CutVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export image or project.
        /// </summary>
        public static string Tooltip_Export {
            get {
                return ResourceManager.GetString("Tooltip_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight an area.
        /// </summary>
        public static string Tooltip_Highlight {
            get {
                return ResourceManager.GetString("Tooltip_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a project or image.
        /// </summary>
        public static string Tooltip_Import {
            get {
                return ResourceManager.GetString("Tooltip_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        public static string Tooltip_New {
            get {
                return ResourceManager.GetString("Tooltip_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a text note.
        /// </summary>
        public static string Tooltip_Note {
            get {
                return ResourceManager.GetString("Tooltip_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        public static string Tooltip_Paste {
            get {
                return ResourceManager.GetString("Tooltip_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot.
        /// </summary>
        public static string Tooltip_Screenshot {
            get {
                return ResourceManager.GetString("Tooltip_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and edit annotations.
        /// </summary>
        public static string Tooltip_Select {
            get {
                return ResourceManager.GetString("Tooltip_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected area to clipboard.
        /// </summary>
        public static string Tooltip_Selection_Copy {
            get {
                return ResourceManager.GetString("Tooltip_Selection_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White out selected area.
        /// </summary>
        public static string Tooltip_Selection_Delete {
            get {
                return ResourceManager.GetString("Tooltip_Selection_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract text from selected area using OCR.
        /// </summary>
        public static string Tooltip_Selection_ExtractText {
            get {
                return ResourceManager.GetString("Tooltip_Selection_ExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} version is available..
        /// </summary>
        public static string Update_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Update_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Annotator - Image Editor.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot annotator software for Windows and Linux.
        ///
        ///Features:
        ///- **Arrows** - Draw attention to specific areas with customizable arrows
        ///- **Callouts** - Add speech bubble annotations with editable text
        ///- **Notes** - Create text boxes for additional information
        ///- **Border Selection** - Highlight areas with bordered rectangles
        ///- **Blur** - Obscure sensitive information with blur effects
        ///- **Selection Tool** - Select portions of the image to copy (Ctrl+C) or delete (Delete key)
        ///- **Cut out vertical a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Winget_Description {
            get {
                return ResourceManager.GetString("Winget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot annotator software for Windows and Linux..
        /// </summary>
        public static string Winget_ShortDescription {
            get {
                return ResourceManager.GetString("Winget_ShortDescription", resourceCulture);
            }
        }
    }
}
