//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenshotAnnotator.Resources;

using System.Globalization;
using System.Resources;

public static class Strings
{
    private static readonly ResourceManager ResourceManagerInstance = new("ScreenshotAnnotator.Resources.Strings", typeof(Strings).Assembly);
    private static readonly CultureInfo ResourceCulture = CultureInfo.CurrentUICulture;

    public static ResourceManager ResourceManager => ResourceManagerInstance;

    public static string Format(string key, params object[] args)
    {
        var format = ResourceManagerInstance.GetString(key, ResourceCulture) ?? key;
        return string.Format(ResourceCulture, format, args);
    }

    public static string _Technical_NsisLanguage => ResourceManagerInstance.GetString("_Technical_NsisLanguage", ResourceCulture) ?? "_Technical_NsisLanguage";
    public static string _Technical_WingetLocale => ResourceManagerInstance.GetString("_Technical_WingetLocale", ResourceCulture) ?? "_Technical_WingetLocale";
    public static string App_DisplayName => ResourceManagerInstance.GetString("App_DisplayName", ResourceCulture) ?? "App_DisplayName";
    public static string Button_Accept => ResourceManagerInstance.GetString("Button_Accept", ResourceCulture) ?? "Button_Accept";
    public static string Button_Cancel => ResourceManagerInstance.GetString("Button_Cancel", ResourceCulture) ?? "Button_Cancel";
    public static string Button_CancelX => ResourceManagerInstance.GetString("Button_CancelX", ResourceCulture) ?? "Button_CancelX";
    public static string Button_Download => ResourceManagerInstance.GetString("Button_Download", ResourceCulture) ?? "Button_Download";
    public static string Button_OK => ResourceManagerInstance.GetString("Button_OK", ResourceCulture) ?? "Button_OK";
    public static string ContextMenu_Delete => ResourceManagerInstance.GetString("ContextMenu_Delete", ResourceCulture) ?? "ContextMenu_Delete";
    public static string ContextMenu_Open => ResourceManagerInstance.GetString("ContextMenu_Open", ResourceCulture) ?? "ContextMenu_Open";
    public static string Copyright_Text => ResourceManagerInstance.GetString("Copyright_Text", ResourceCulture) ?? "Copyright_Text";
    public static string Dialog_Export_Title => ResourceManagerInstance.GetString("Dialog_Export_Title", ResourceCulture) ?? "Dialog_Export_Title";
    public static string Dialog_Import_Title => ResourceManagerInstance.GetString("Dialog_Import_Title", ResourceCulture) ?? "Dialog_Import_Title";
    public static string FileType_AllFiles => ResourceManagerInstance.GetString("FileType_AllFiles", ResourceCulture) ?? "FileType_AllFiles";
    public static string FileType_AllSupported => ResourceManagerInstance.GetString("FileType_AllSupported", ResourceCulture) ?? "FileType_AllSupported";
    public static string FileType_AnnotatorProject => ResourceManagerInstance.GetString("FileType_AnnotatorProject", ResourceCulture) ?? "FileType_AnnotatorProject";
    public static string FileType_Images => ResourceManagerInstance.GetString("FileType_Images", ResourceCulture) ?? "FileType_Images";
    public static string FileType_JPEG => ResourceManagerInstance.GetString("FileType_JPEG", ResourceCulture) ?? "FileType_JPEG";
    public static string FileType_PNG => ResourceManagerInstance.GetString("FileType_PNG", ResourceCulture) ?? "FileType_PNG";
    public static string FileType_WebP => ResourceManagerInstance.GetString("FileType_WebP", ResourceCulture) ?? "FileType_WebP";
    public static string Header_ScreenshotAnnotator => ResourceManagerInstance.GetString("Header_ScreenshotAnnotator", ResourceCulture) ?? "Header_ScreenshotAnnotator";
    public static string ImproveIt_Message => ResourceManagerInstance.GetString("ImproveIt_Message", ResourceCulture) ?? "ImproveIt_Message";
    public static string Installer_AdminRequired => ResourceManagerInstance.GetString("Installer_AdminRequired", ResourceCulture) ?? "Installer_AdminRequired";
    public static string Installer_AdminRequiredDetailed => ResourceManagerInstance.GetString("Installer_AdminRequiredDetailed", ResourceCulture) ?? "Installer_AdminRequiredDetailed";
    public static string Installer_AllUsersDescription => ResourceManagerInstance.GetString("Installer_AllUsersDescription", ResourceCulture) ?? "Installer_AllUsersDescription";
    public static string Installer_AllUsersOption => ResourceManagerInstance.GetString("Installer_AllUsersOption", ResourceCulture) ?? "Installer_AllUsersOption";
    public static string Installer_ArchRequired => ResourceManagerInstance.GetString("Installer_ArchRequired", ResourceCulture) ?? "Installer_ArchRequired";
    public static string Installer_CurrentUserDescription => ResourceManagerInstance.GetString("Installer_CurrentUserDescription", ResourceCulture) ?? "Installer_CurrentUserDescription";
    public static string Installer_CurrentUserOption => ResourceManagerInstance.GetString("Installer_CurrentUserOption", ResourceCulture) ?? "Installer_CurrentUserOption";
    public static string Installer_InstallingFor => ResourceManagerInstance.GetString("Installer_InstallingFor", ResourceCulture) ?? "Installer_InstallingFor";
    public static string Installer_InstallModeDescription => ResourceManagerInstance.GetString("Installer_InstallModeDescription", ResourceCulture) ?? "Installer_InstallModeDescription";
    public static string Installer_InstallModeSubtitle => ResourceManagerInstance.GetString("Installer_InstallModeSubtitle", ResourceCulture) ?? "Installer_InstallModeSubtitle";
    public static string Installer_InstallModeTitle => ResourceManagerInstance.GetString("Installer_InstallModeTitle", ResourceCulture) ?? "Installer_InstallModeTitle";
    public static string Installer_LaunchApp => ResourceManagerInstance.GetString("Installer_LaunchApp", ResourceCulture) ?? "Installer_LaunchApp";
    public static string Menu_EnablePrintScreenHotkey => ResourceManagerInstance.GetString("Menu_EnablePrintScreenHotkey", ResourceCulture) ?? "Menu_EnablePrintScreenHotkey";
    public static string Menu_Export => ResourceManagerInstance.GetString("Menu_Export", ResourceCulture) ?? "Menu_Export";
    public static string Menu_File => ResourceManagerInstance.GetString("Menu_File", ResourceCulture) ?? "Menu_File";
    public static string Menu_Import => ResourceManagerInstance.GetString("Menu_Import", ResourceCulture) ?? "Menu_Import";
    public static string Menu_License => ResourceManagerInstance.GetString("Menu_License", ResourceCulture) ?? "Menu_License";
    public static string Menu_New => ResourceManagerInstance.GetString("Menu_New", ResourceCulture) ?? "Menu_New";
    public static string Menu_OpenLogsFolder => ResourceManagerInstance.GetString("Menu_OpenLogsFolder", ResourceCulture) ?? "Menu_OpenLogsFolder";
    public static string Menu_OpenProjectsFolder => ResourceManagerInstance.GetString("Menu_OpenProjectsFolder", ResourceCulture) ?? "Menu_OpenProjectsFolder";
    public static string Menu_Options => ResourceManagerInstance.GetString("Menu_Options", ResourceCulture) ?? "Menu_Options";
    public static string Menu_WebSite => ResourceManagerInstance.GetString("Menu_WebSite", ResourceCulture) ?? "Menu_WebSite";
    public static string Panel_Projects => ResourceManagerInstance.GetString("Panel_Projects", ResourceCulture) ?? "Panel_Projects";
    public static string Panel_Properties => ResourceManagerInstance.GetString("Panel_Properties", ResourceCulture) ?? "Panel_Properties";
    public static string Props_Bold => ResourceManagerInstance.GetString("Props_Bold", ResourceCulture) ?? "Props_Bold";
    public static string Props_Color => ResourceManagerInstance.GetString("Props_Color", ResourceCulture) ?? "Props_Color";
    public static string Props_Font => ResourceManagerInstance.GetString("Props_Font", ResourceCulture) ?? "Props_Font";
    public static string Props_Italic => ResourceManagerInstance.GetString("Props_Italic", ResourceCulture) ?? "Props_Italic";
    public static string Props_Size => ResourceManagerInstance.GetString("Props_Size", ResourceCulture) ?? "Props_Size";
    public static string Screenshot_Instructions => ResourceManagerInstance.GetString("Screenshot_Instructions", ResourceCulture) ?? "Screenshot_Instructions";
    public static string Tool_Arrow => ResourceManagerInstance.GetString("Tool_Arrow", ResourceCulture) ?? "Tool_Arrow";
    public static string Tool_Blur => ResourceManagerInstance.GetString("Tool_Blur", ResourceCulture) ?? "Tool_Blur";
    public static string Tool_Border => ResourceManagerInstance.GetString("Tool_Border", ResourceCulture) ?? "Tool_Border";
    public static string Tool_Callout => ResourceManagerInstance.GetString("Tool_Callout", ResourceCulture) ?? "Tool_Callout";
    public static string Tool_Copy => ResourceManagerInstance.GetString("Tool_Copy", ResourceCulture) ?? "Tool_Copy";
    public static string Tool_CutHorizontal => ResourceManagerInstance.GetString("Tool_CutHorizontal", ResourceCulture) ?? "Tool_CutHorizontal";
    public static string Tool_CutVertical => ResourceManagerInstance.GetString("Tool_CutVertical", ResourceCulture) ?? "Tool_CutVertical";
    public static string Tool_Export => ResourceManagerInstance.GetString("Tool_Export", ResourceCulture) ?? "Tool_Export";
    public static string Tool_Highlight => ResourceManagerInstance.GetString("Tool_Highlight", ResourceCulture) ?? "Tool_Highlight";
    public static string Tool_Import => ResourceManagerInstance.GetString("Tool_Import", ResourceCulture) ?? "Tool_Import";
    public static string Tool_New => ResourceManagerInstance.GetString("Tool_New", ResourceCulture) ?? "Tool_New";
    public static string Tool_Note => ResourceManagerInstance.GetString("Tool_Note", ResourceCulture) ?? "Tool_Note";
    public static string Tool_Paste => ResourceManagerInstance.GetString("Tool_Paste", ResourceCulture) ?? "Tool_Paste";
    public static string Tool_Screenshot => ResourceManagerInstance.GetString("Tool_Screenshot", ResourceCulture) ?? "Tool_Screenshot";
    public static string Tool_Select => ResourceManagerInstance.GetString("Tool_Select", ResourceCulture) ?? "Tool_Select";
    public static string Tooltip_Arrow => ResourceManagerInstance.GetString("Tooltip_Arrow", ResourceCulture) ?? "Tooltip_Arrow";
    public static string Tooltip_Blur => ResourceManagerInstance.GetString("Tooltip_Blur", ResourceCulture) ?? "Tooltip_Blur";
    public static string Tooltip_Border => ResourceManagerInstance.GetString("Tooltip_Border", ResourceCulture) ?? "Tooltip_Border";
    public static string Tooltip_Callout => ResourceManagerInstance.GetString("Tooltip_Callout", ResourceCulture) ?? "Tooltip_Callout";
    public static string Tooltip_CollapseExpandPanel => ResourceManagerInstance.GetString("Tooltip_CollapseExpandPanel", ResourceCulture) ?? "Tooltip_CollapseExpandPanel";
    public static string Tooltip_Copy => ResourceManagerInstance.GetString("Tooltip_Copy", ResourceCulture) ?? "Tooltip_Copy";
    public static string Tooltip_CutHorizontal => ResourceManagerInstance.GetString("Tooltip_CutHorizontal", ResourceCulture) ?? "Tooltip_CutHorizontal";
    public static string Tooltip_CutVertical => ResourceManagerInstance.GetString("Tooltip_CutVertical", ResourceCulture) ?? "Tooltip_CutVertical";
    public static string Tooltip_Export => ResourceManagerInstance.GetString("Tooltip_Export", ResourceCulture) ?? "Tooltip_Export";
    public static string Tooltip_Highlight => ResourceManagerInstance.GetString("Tooltip_Highlight", ResourceCulture) ?? "Tooltip_Highlight";
    public static string Tooltip_Import => ResourceManagerInstance.GetString("Tooltip_Import", ResourceCulture) ?? "Tooltip_Import";
    public static string Tooltip_New => ResourceManagerInstance.GetString("Tooltip_New", ResourceCulture) ?? "Tooltip_New";
    public static string Tooltip_Note => ResourceManagerInstance.GetString("Tooltip_Note", ResourceCulture) ?? "Tooltip_Note";
    public static string Tooltip_Paste => ResourceManagerInstance.GetString("Tooltip_Paste", ResourceCulture) ?? "Tooltip_Paste";
    public static string Tooltip_Screenshot => ResourceManagerInstance.GetString("Tooltip_Screenshot", ResourceCulture) ?? "Tooltip_Screenshot";
    public static string Tooltip_Select => ResourceManagerInstance.GetString("Tooltip_Select", ResourceCulture) ?? "Tooltip_Select";
    public static string Ocr_Engine => ResourceManagerInstance.GetString("Ocr_Engine", ResourceCulture) ?? "Ocr_Engine";
    public static string Ocr_ExtractButton => ResourceManagerInstance.GetString("Ocr_ExtractButton", ResourceCulture) ?? "Ocr_ExtractButton";
    public static string Ocr_Languages => ResourceManagerInstance.GetString("Ocr_Languages", ResourceCulture) ?? "Ocr_Languages";
    public static string Ocr_NoEngines => ResourceManagerInstance.GetString("Ocr_NoEngines", ResourceCulture) ?? "Ocr_NoEngines";
    public static string Ocr_NoEnginesHelp => ResourceManagerInstance.GetString("Ocr_NoEnginesHelp", ResourceCulture) ?? "Ocr_NoEnginesHelp";
    public static string Ocr_Processing => ResourceManagerInstance.GetString("Ocr_Processing", ResourceCulture) ?? "Ocr_Processing";
    public static string Ocr_Result => ResourceManagerInstance.GetString("Ocr_Result", ResourceCulture) ?? "Ocr_Result";
    public static string Ocr_TesseractLangHint => ResourceManagerInstance.GetString("Ocr_TesseractLangHint", ResourceCulture) ?? "Ocr_TesseractLangHint";
    public static string Ocr_Title => ResourceManagerInstance.GetString("Ocr_Title", ResourceCulture) ?? "Ocr_Title";
    public static string Selection_Copy => ResourceManagerInstance.GetString("Selection_Copy", ResourceCulture) ?? "Selection_Copy";
    public static string Selection_Delete => ResourceManagerInstance.GetString("Selection_Delete", ResourceCulture) ?? "Selection_Delete";
    public static string Selection_ExtractText => ResourceManagerInstance.GetString("Selection_ExtractText", ResourceCulture) ?? "Selection_ExtractText";
    public static string Tooltip_Selection_Copy => ResourceManagerInstance.GetString("Tooltip_Selection_Copy", ResourceCulture) ?? "Tooltip_Selection_Copy";
    public static string Tooltip_Selection_Delete => ResourceManagerInstance.GetString("Tooltip_Selection_Delete", ResourceCulture) ?? "Tooltip_Selection_Delete";
    public static string Tooltip_Selection_ExtractText => ResourceManagerInstance.GetString("Tooltip_Selection_ExtractText", ResourceCulture) ?? "Tooltip_Selection_ExtractText";
    public static string Update_NewVersionAvailable => ResourceManagerInstance.GetString("Update_NewVersionAvailable", ResourceCulture) ?? "Update_NewVersionAvailable";
    public static string Window_Title => ResourceManagerInstance.GetString("Window_Title", ResourceCulture) ?? "Window_Title";
    public static string Winget_Description => ResourceManagerInstance.GetString("Winget_Description", ResourceCulture) ?? "Winget_Description";
    public static string Winget_ShortDescription => ResourceManagerInstance.GetString("Winget_ShortDescription", ResourceCulture) ?? "Winget_ShortDescription";
}

